### ISSUE TITLE
Optimize hostURL function

### ISSUE THREAD

**Issue by nikitafomin** [fs/ios-base-swift#36]
I think we should keep simple our code. Building of hostURL looks strange. We already have URL_SCHEME and URL_HOST in plist. I think we should use this variables.

**Comment by nikitafomin** [comment]
And we should add new User-Defined Setting for version of API

**Comment by nikitafomin** [comment]
Check https://github.com/fs/ios-base-swift/pull/45

**Comment by kruperfone** [comment]
done
